version: '3'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - mongodata:/data/db
volumes:
  mongodata: